# This workflow will install Python YAPF and check format.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python YAPF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yapf==0.30.0
    - name: Check format with YAPF
      run: |
        yapf --style=google -d -r .
