name: Python Tutorials

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7.17, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install . papermill matplotlib plotly jupyter hyperopt torch torchvision
    - name: Test with pytest
      run: |
        cd tutorials/
        papermill example_ising.ipynb /dev/null
        papermill hpo_demo.ipynb /dev/null
        papermill ising_tutorial.ipynb /dev/null
        papermill RBM_tutorial.ipynb /dev/null
